update: GHA workflows
pulumiverse/pulumi-redpanda pull request #2
Opened 2024-05-17 02:53 UTC by videmsky

2024-05-20 13:29 UTC, ringods requested changes

2024-05-20 13:29 UTC, ringods commented on .github/workflows/upgrade-provider.yml
> +          username: "Ringo De Smet"
@videmsky I don't need the credit for a bridge update. This info is used as the git commit info, so preferably make this yours.

2024-05-20 17:46 UTC, videmsky commented on .github/workflows/upgrade-provider.yml
> +          username: "Ringo De Smet"
ha ha, sorry for the copy pasta! fixed.

2024-05-21 07:35 UTC, ringods approved these changes

2024-05-22 18:26 UTC, merged